In [1]:
import numpy as np

a=np.array([1,2,3])

print(a[1])

2


In [2]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
element = matrix[1,2]
print(element)

6


In [6]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [8]:
print(np.empty(5))

[1. 1. 1. 1. 1.]


In [12]:
print(np.arange(100))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [14]:
print(np.linspace(0,10,num=5))

[ 0.   2.5  5.   7.5 10. ]


In [15]:
a = np.ones(5,dtype=np.int64)
print(a)

[1 1 1 1 1]


In [25]:
arr = [45,10,99,123,4,0]
arr = np.sort(arr)
print(arr)

arr = np.sort(arr)[::-1]
print(arr)

[  0   4  10  45  99 123]
[123  99  45  10   4   0]


In [28]:
print(np.append(arr,100))

[123  99  45  10   4   0 100]


In [29]:
arr = np.delete(arr,0)
print(arr)

[99 45 10  4  0]


In [41]:
arr = np.array([[1,9,0],
               [3,8,7],
               [4,1,9]])
sep_theo_hang = np.sort(arr,axis=1) #tang dan,axis=1 hang
print(sep_theo_hang)

sep_theo_cot = -np.sort(-arr,axis=0) #giam dan,axis=0 cot
print(sep_theo_cot)

print(arr.ndim) # so chieu
print(arr.size) # kich thuoc(so phan tu)
print(arr.shape) # ma tran axb

[[0 1 9]
 [3 7 8]
 [1 4 9]]
[[4 9 9]
 [3 8 7]
 [1 1 0]]
2
9
(3, 3)


In [44]:
# chuyển đổi dữ liệu
arr = np.array([1,2,3,4,5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [48]:
# thay đổi hình dạng của mảng:
arr= np.array([74,6,4,5,7,98,21,5])
print(arr.reshape(2,4))

[[74  6  4  5]
 [ 7 98 21  5]]


In [50]:
arr = np.array([[1,9,0],
               [3,8,7],
               [4,1,9]])
new = arr.flatten()
print(new)
print(arr.T)

[1 9 0 3 8 7 4 1 9]
[[1 3 4]
 [9 8 1]
 [0 7 9]]


In [53]:
arr1 = np.array([1,5,8])
arr2 = np.array([4,8,2])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 5 8 4 8 2]
